In [1]:
import torch

In [3]:
#DOMANDA 9
# torch.Tensor([[1,2,3],[5,4,3]]) -> 2,3
# torch.Tensor([[[2,1],[3,3],[2,3]],[[2,2],[3,2],[4,5]]]) -> 2,3,2
# torch.Tensor([1,2,3]) -> 3

print(torch.Tensor([[1,2,3],[5,4,3]]).shape)
print(torch.Tensor([[[2,1],[3,3],[2,3]],[[2,2],[3,2],[4,5]]]).shape)
print(torch.Tensor([1,2,3]).shape)



torch.Size([2, 3])
torch.Size([2, 3, 2])
torch.Size([3])


In [4]:
#DOMANDA 10
# t = torch.Tensor([[4,8,2],[6,6,9]])
# IntTensor
# Ritorna 6
# [16,64,4]
# Nella prima dividiamo, nella seconda dividiamo e assegniamo. Meglio la prima

In [5]:
#DOMANDA 11
# 1

t = torch.Tensor([[4,8,2],[6,6,9]])
n = t.numpy()
n/=2
print(t[0,2])

tensor(1.)


In [8]:
#DOMANDA 12
# 6

x = torch.Tensor([6])
x.requires_grad_(True)
y = 0.5 * x**2
y.backward()
print(x.grad)

tensor([6.])


In [9]:
#DOMANDA 13
# 18?
y = x**2
y.backward()
print(x.grad)

tensor([18.])


In [10]:
#DOMANDA 14
# 3 e 3
x = torch.Tensor([3]); x.requires_grad_(True)
y = torch.Tensor([6]); y.requires_grad_(True)
z = 0.5*x**2+3*y
z.backward()
print(x.grad)
print(y.grad)

tensor([3.])
tensor([3.])


In [12]:
#ESERCIZIO 11
a = torch.Tensor([[1,3,6],[4,5,9]])
b = torch.Tensor([[6,7,9],[9,8,2]])

c = torch.add(a,b)
print(c)

tensor([[ 7., 10., 15.],
        [13., 13., 11.]])


In [13]:
a.sub_(b)
print(a)

tensor([[-5., -4., -3.],
        [-5., -3.,  7.]])


In [19]:
valori_max, indici_max = a.max(-1)
print(valori_max)

tensor([-3.,  7.])


In [23]:
print(b.sum(-1))

tensor([22., 19.])


In [25]:
#Esercizio 12
f = lambda x,y: (x / y**x) - y**3
x = torch.Tensor([0]); x.requires_grad_(True)
y = torch.Tensor([8]); y.requires_grad_(True)

z = f(x,y)
print(z)

z.backward()
print(x.grad)
print(y.grad)

tensor([-512.], grad_fn=<SubBackward0>)
tensor([1.])
tensor([-192.])
